ps<-setClass("Primerset", slots=c(oldsequence="character", primers="list", newsequence="character"))
pc<-setClass("Primer", slots=c(prefix="character" ,restriction_enzyme="character", suffix="character", vector="character", overhang="character", extra="character" ,binding_sequence="character", temperature="numeric", difference="numeric"))
pc_msd<-setClass("Primer_MSD", contains="Primer")
pc_spm<-setClass("Primer_SPM", contains="Primer")
fragment<-setClass("Fragment", slots=c(start="numeric", stop="numeric", start_mutation="vector", stop_mutation="vector"))
eps<-setClass("Extended_Primerset", contains="Primerset", slots=c(fragments="list"))
